package com.augmentum.ot.dataObject.constant;

public class ItemTypeConstants {
	
	//Trainee    Feedback to course ...
	public static String ASSESS_COURSE = "assessCourse";
	//Trainer    Log trainee attendance and feedback to course ...
	public static String ASSESS_TRAINEES = "assessTrainees";
	//Training Master    Publish your plan ...
	public static String PUBLISH_PLAN = "publishPlan";
	//Training Master    Fill in remaining info of your plan ...
	public static String UNCOMPLETED_PLAN = "uncompletedPlan";
	//Training Master    Assess trainers for your plan ...
	public static String MASTER_ASSESS_TRAINERS = "masterAssessTrainers";
	//Trainer    Feedback to plan ...
	public static String TRAINER_ASSESS_PLAN = "assessPlan";
	//Trainee    Feedback to plan ...
	public static String TRAINEE_ASSESS_PLAN = "assessPlan";

}
