use ot2;
-- initialize employee
insert into `employee` values ('1', 'HansenOuyang@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'T00390', 'Hansen Ouyang', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
insert into `employee` values ('2', 'MargaretWang@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'T04024', 'Margaret Wang', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
insert into `employee` values ('3', 'Jasonliu@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'T04114', 'Jason Liu', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
insert into `employee` values ('4', 'TonyLi@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'YT00169', 'Tony Li', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
insert into `employee` values ('5', 'LeviZhou@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'YT00200', 'Levi Zhou', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
insert into `employee` values ('6', 'CarlKong@augmentum.com.cn','HansenOuyang@augmentum.com.cn', 'YT00205', 'Carl Kong', 'e397433ba52b69656be325c89581b13a', 'IES_SH', '0');
-- initialize employee_role_map
insert into `employee_role_level_map` values ('1', '1', '3', null);
insert into `employee_role_level_map` values ('2', '1', '2', null);
insert into `employee_role_level_map` values ('3', '1', '1', null);
insert into `employee_role_level_map` values ('4', '2', '3', null);
insert into `employee_role_level_map` values ('5', '2', '2', null);
insert into `employee_role_level_map` values ('6', '2', '1', null);

-- initialize course_type_tb
insert into course_type values(1,'Culture&Policy');
insert into course_type values(2,'Technical');
insert into course_type values(3,'Project&Management');
insert into course_type values(4,'Leadership&Management');
insert into course_type values(5,'English');
insert into course_type values(6,'Soft&Skills');

-- initialize category_tb
insert into course_tag value(1,'management');
insert into course_tag value(2,'project');
insert into course_tag value(3,'policy');
insert into course_tag value(4,'java');
insert into course_tag value(5,'c++');

-- initialize optional_column_tb
insert into custom_column values(1,0,'ID',0,1,0);
insert into custom_column values(2,0,'Name',0,1,0);
insert into custom_column values(3,0,'Brief',0,1,0);
insert into custom_column values(4,0,'Target Attendees',0,1,1);
insert into custom_column values(5,0,'Duration',0,1,1);
insert into custom_column values(6,0,'Type',0,1,1);
insert into custom_column values(7,0,'Tag',0,1,1);
insert into custom_column values(8,0,'If-Certificated',0,1,1);
insert into custom_column values(9,0,'Update History',0,1,1);
insert into custom_column values(10,0,'Author',0,1,1);
insert into custom_column values(11,0,'History Trainer',0,1,1);

insert into custom_column values(12,2,'ID',0,1,0);
insert into custom_column values(13,2,'Name',0,1,0);
insert into custom_column values(14,2,'Brief',0,1,0);
insert into custom_column values(15,2,'Type',0,1,1);
insert into custom_column values(16,2,'Tag',0,1,1);
insert into custom_column values(17,2,'Date',0,1,1);
insert into custom_column values(18,2,'Creator',0,1,1);

insert into custom_column values(19,1,'programId',0,1,0);
insert into custom_column values(20,1,'programName',0,1,0);
insert into custom_column values(21,1,'programBrief',0,1,0);
insert into custom_column values(22,1,'programTargetAttendees',0,1,1);
insert into custom_column values(23,1,'programCategory',0,1,1);
insert into custom_column values(24,1,'programAttachment',0,1,1);
insert into custom_column values(25,1,'programCreator',0,1,1);

insert into custom_column values(26,3,'ID',0,1,0);
insert into custom_column values(27,3,'Name',0,1,0);
insert into custom_column values(28,3,'Brief',0,1,0);
insert into custom_column values(29,3,'Target Attendees',0,1,1);
insert into custom_column values(30,3,'Duration',0,1,1);
insert into custom_column values(31,3,'Type',0,1,1);
insert into custom_column values(32,3,'Tag',0,1,1);
insert into custom_column values(33,3,'If-Certificated',0,1,1);
insert into custom_column values(34,3,'Update History',0,1,1);
insert into custom_column values(35,3,'Attachment',0,1,1);
insert into custom_column values(36,3,'Author',0,1,1);
insert into custom_column values(37,3,'History Trainer',0,1,1);

insert into custom_column values(38,4,'ID',0,1,0);
insert into custom_column values(39,4,'Name',0,1,0);
insert into custom_column values(40,4,'Brief',0,1,0);
insert into custom_column values(41,4,'Type',0,1,1);
insert into custom_column values(42,4,'Tag',0,1,1);
insert into custom_column values(43,4,'Date',0,1,1);
insert into custom_column values(44,4,'Creator',0,1,1);

-- initialize page_size
insert into page_size values(1,0,10,0);
insert into page_size values(2,0,15,0);
insert into page_size values(3,0,20,0);
insert into page_size values(4,2,10,0);
insert into page_size values(5,2,15,0);
insert into page_size values(6,2,20,0);
insert into page_size values(7,2,25,0);
insert into page_size values(8,1,10,0);
insert into page_size values(9,1,15,0);
insert into page_size values(10,1,20,0);
insert into page_size values(11,1,25,0);
insert into page_size values(12,1,30,0);
insert into page_size values(13,4,8,0);
insert into page_size values(14,3,8,0);

-- initialize plan_tag
insert into plan_tag value(1,'management');
insert into plan_tag value(2,'project');
insert into plan_tag value(3,'policy');
insert into plan_tag value(4,'java');
insert into plan_tag value(5,'c++');

-- initialize plan_type
insert into plan_type values(1, 'Invited');
insert into plan_type values(2, 'Public');

-- initialize role
insert into role (id,name) values(3,"Admin");
insert into role (id,name) values(2,"Training Master");
insert into role (id,name) values(1,"Trainer");

-- initialize privilege
insert into `privilege` values ('1', 'course[searchcourse]', '0');
insert into `privilege` values ('2', 'course[presearchcourse]', '1');
insert into `privilege` values ('3', 'course[createcourse]', '2');
insert into `privilege` values ('4', 'course[viewtherecorddetail]', '3');
insert into `privilege` values ('5', 'course[toeditcourse]', '4');
insert into `privilege` values ('6', 'course[viewcoursedetail]', '5');
insert into `privilege` values ('7', 'course[deletecourse]', '6');
insert into `privilege` values ('8', 'course[editcourse]', '7');
insert into `privilege` values ('9', 'course[getcourseattachmentsbyid]', '8');
insert into `privilege` values ('10', 'course[clearoperation]', '9');
insert into `privilege` values ('11', 'plan[createplan]', '10');
insert into `privilege` values ('12', 'plan[editplan]', '11');
insert into `privilege` values ('13', 'plan[courselistconfirm]', '12');
insert into `privilege` values ('14', 'plan[searchplan]', '13');
insert into `privilege` values ('15', 'plan[presearchplan]', '14');
insert into `privilege` values ('16', 'plan[findactualcoursesbyplanid]', '15');
insert into `privilege` values ('17', 'plan[viewtherecorddetail]', '16');
insert into `privilege` values ('18', 'plan[viewplandetail]', '17');
insert into `privilege` values ('19', 'plan[toeditplan]', '18');
insert into `privilege` values ('20', 'plan[clearoperation]', '19');
insert into `privilege` values ('21', 'plan[deleteplan]', '20');
insert into `privilege` values ('22', 'plan[publishplan]', '21');
insert into `privilege` values ('23', 'plan[cancelplan]', '22');
insert into `privilege` values ('24', 'plan[findactualcoursebyid]', '23');
insert into `privilege` values ('26', 'plan[getplanattachmentsbyid]', '25');
insert into `privilege` values ('27', 'assessment[searchdata_searchtrainer2plandata]', '26');
insert into `privilege` values ('28', 'assessment[create_createtrainer2planassessment]', '27');
insert into `privilege` values ('29', 'assessment[searchdata_searchtrainee2coursedata]', '28');
insert into `privilege` values ('30', 'assessment[create_createtrainee2courseassessment]', '29');
insert into `privilege` values ('31', 'assessment[searchdata_searchmaster2trainerdata]', '30');
insert into `privilege` values ('32', 'assessment[create_createmaster2trainerassessment]', '31');
insert into `privilege` values ('33', 'assessment[searchdata_searchtrainee2plandata]', '32');
insert into `privilege` values ('34', 'assessment[create_createtrainee2planassessment]', '33');
insert into `privilege` values ('35', 'assessment[searchdata_searchtrainer2traineedata]', '34');
insert into `privilege` values ('36', 'assessment[create_createtrainer2traineeassessment]', '35');
insert into `privilege` values ('37', 'assessment[viewactualcourselistandtraineelist]', '36');
insert into `privilege` values ('38', 'assessment[viewassessmentbyplanidandtraineeid]', '37');
insert into `privilege` values ('39', 'assessment[viewassessmentbyplanidandactualcourseid]', '38');
insert into `privilege` values ('40', 'assessment[viewtrainerandactualcourselistbyplanid]', '39');
insert into `privilege` values ('41', 'assessment[viewmastertotrainerassessmentbyplanidandtrainerid]', '40');
insert into `privilege` values ('42', 'assessment[viewtraineestotrainerassessmentbyactualcourseidandtrainerid]', '41');
insert into `privilege` values ('43', 'assessment[viewtraineestoplaninfo]', '42');
insert into `privilege` values ('44', 'assessment[viewtrainerstoplaninfo]', '43');
insert into `privilege` values ('45', 'assessment[getactualcourseneedassessment]', '44');
insert into `privilege` values ('46', 'assessment[viewtraineestocourseinfo]', '45');
insert into `privilege` values ('47', 'assessment[viewtrainertocourseinfo]', '46');
insert into `privilege` values ('48', 'attachment[downloadattachment]', '47');
insert into `privilege` values ('49', 'attachment[uploadimage]', '48');
insert into `privilege` values ('50', 'attachment[uploadcourseattachment]', '49');
insert into `privilege` values ('51', 'attachment[uploadplanattachment]', '50');
insert into `privilege` values ('52', 'attachment[uploadactualcourseattachment]', '51');
insert into `privilege` values ('53', 'attachment[uploadplansessionattachment]', '52');
insert into `privilege` values ('54', 'searchcommon[searchcommon_finddatalistinfo]', '53');
insert into `privilege` values ('55', 'searchcommon[searchcommon_updateshowfields]', '54');
insert into `privilege` values ('56', 'searchcommon[searchcommon_updateshowsize]', '55');
insert into `privilege` values ('57', 'searchcommon[searchcommon_findcoursetypes]', '56');
insert into `privilege` values ('58', 'searchcommon[searchcommon_findcoursetags]', '57');
insert into `privilege` values ('59', 'searchcommon[searchcommon_findplantypes]', '58');
insert into `privilege` values ('60', 'searchcommon[searchcommon_findplantags]', '59');
insert into `privilege` values ('61', 'plan[viewnextrecorddetail]', '60');
insert into `privilege` values ('62', 'plan[viewpreviousrecorddetail]', '61');
insert into `privilege` values ('63', 'course[viewnextrecorddetail]', '62');
insert into `privilege` values ('64', 'course[viewpreviousrecorddetail]', '63');
insert into `privilege` values ('65', 'searchcommon[searchcommon_findallemployeenames]', '64');
insert into `privilege` values ('66', 'rolelist[searchrolelist]', '65');
insert into `privilege` values ('67', 'rolelist[saverolelist]', '66');
insert into `privilege` values ('68', 'dashboard[getplanandcourselist]', '67');
insert into `privilege` values ('69', 'dashboard[newpublicplan]', '68');
insert into `privilege` values ('70', 'dashboard[joinorquitplan]', '69');
insert into `privilege` values ('71', 'dashboard[gettodolistforrole]', '70');
insert into `privilege` values ('72', 'dashboard[getcourselistforpublishplan]', '71');
insert into `privilege` values ('73', '[toi18n]', '72');
insert into `privilege` values ('74', '[ajaxerrorhandle]', '73');
insert into `privilege` values ('75', 'dashboard[dashboard_dashboard]', '74');
insert into `privilege` values ('76', 'plan[plan_createPlan]', '75');
insert into `privilege` values ('77', 'plan[plan_searchPlan]', '76');
insert into `privilege` values ('78', 'plan[plan_myPlan]', '77');
insert into `privilege` values ('79', 'roleList[roleList_roleList]', '78');
insert into `privilege` values ('80', 'course[course_searchCourse]', '79');
insert into `privilege` values ('81', 'course[course_createCourse]', '80');
insert into `privilege` values ('82', 'course[course_myCourse]', '81');
insert into `privilege` values ('83', 'plan[searchMyPlan]', '82');
insert into `privilege` values ('84', 'assessment[prepareViewAllAssessment]', '83');
insert into `privilege` values ('85', 'plan[getPlanInfo]', '84');
insert into `privilege` values ('86', 'plan[getActualCourseInfo]', '85');
insert into `privilege` values ('87', 'plan[plan_mycourse]', '86');
insert into `privilege` values ('88', 'plan[searchmycourse]', '87');
insert into `privilege` values ('89', 'plan[getactualcourseattachmentsbyid]', '88');
insert into `privilege` values ('90', 'plan[applyleaveplan]', '89');
insert into `privilege` values ('91', 'plan[applyleavecourse]', '90');
insert into `privilege` values ('92', 'plan[applybackcourse]', '91');
insert into `privilege` values ('93', 'plan[applybackplan]', '92');
insert into `privilege` values ('94', 'assessment[edit_editTrianer2planAssessment]', '93');
insert into `privilege` values ('95', 'assessment[edit_editTrainee2courseAssessment]', '94');
insert into `privilege` values ('96', 'assessment[edit_editMaster2trainerAssessment]', '95');
insert into `privilege` values ('97', 'assessment[ignore_ignoreTrainer2planAssessment]', '96');
insert into `privilege` values ('98', 'assessment[ignore_ignoreTrainee2courseAssessment]', '97');
insert into `privilege` values ('99', 'assessment[ignore_ignoreMaster2trainerAssessment]', '98');
insert into `privilege` values ('100', 'assessment[ignore_ignoreTrainee2planAssessment]', '99');
insert into `privilege` values ('101', 'assessment[ignore_ignoreTrainer2Trainee]', '100');
insert into `privilege` values ('102', 'assessment[viewAverageScoreOfTrainer]', '101');
 
-- initialize role_privilege_map
insert into `role_privilege_map` values ('3', '1');
insert into `role_privilege_map` values ('3', '2');
insert into `role_privilege_map` values ('3', '3');
insert into `role_privilege_map` values ('3', '4');
insert into `role_privilege_map` values ('3', '5');
insert into `role_privilege_map` values ('3', '6');
insert into `role_privilege_map` values ('3', '7');
insert into `role_privilege_map` values ('3', '8');
insert into `role_privilege_map` values ('3', '9');
insert into `role_privilege_map` values ('3', '10');
insert into `role_privilege_map` values ('3', '11');
insert into `role_privilege_map` values ('3', '12');
insert into `role_privilege_map` values ('3', '13');
insert into `role_privilege_map` values ('3', '14');
insert into `role_privilege_map` values ('3', '15');
insert into `role_privilege_map` values ('3', '16');
insert into `role_privilege_map` values ('3', '17');
insert into `role_privilege_map` values ('3', '18');
insert into `role_privilege_map` values ('3', '19');
insert into `role_privilege_map` values ('3', '20');
insert into `role_privilege_map` values ('3', '21');
insert into `role_privilege_map` values ('3', '22');
insert into `role_privilege_map` values ('3', '23');
insert into `role_privilege_map` values ('3', '24');
insert into `role_privilege_map` values ('3', '26');
insert into `role_privilege_map` values ('3', '27');
insert into `role_privilege_map` values ('3', '28');
insert into `role_privilege_map` values ('3', '29');
insert into `role_privilege_map` values ('3', '30');
insert into `role_privilege_map` values ('3', '31');
insert into `role_privilege_map` values ('3', '32');
insert into `role_privilege_map` values ('3', '33');
insert into `role_privilege_map` values ('3', '34');
insert into `role_privilege_map` values ('3', '35');
insert into `role_privilege_map` values ('3', '36');
insert into `role_privilege_map` values ('3', '37');
insert into `role_privilege_map` values ('3', '38');
insert into `role_privilege_map` values ('3', '39');
insert into `role_privilege_map` values ('3', '40');
insert into `role_privilege_map` values ('3', '41');
insert into `role_privilege_map` values ('3', '42');
insert into `role_privilege_map` values ('3', '43');
insert into `role_privilege_map` values ('3', '44');
insert into `role_privilege_map` values ('3', '45');
insert into `role_privilege_map` values ('3', '46');
insert into `role_privilege_map` values ('3', '47');
insert into `role_privilege_map` values ('3', '48');
insert into `role_privilege_map` values ('3', '49');
insert into `role_privilege_map` values ('3', '50');
insert into `role_privilege_map` values ('3', '51');
insert into `role_privilege_map` values ('3', '52');
insert into `role_privilege_map` values ('3', '53');
insert into `role_privilege_map` values ('3', '54');
insert into `role_privilege_map` values ('3', '55');
insert into `role_privilege_map` values ('3', '56');
insert into `role_privilege_map` values ('3', '57');
insert into `role_privilege_map` values ('3', '58');
insert into `role_privilege_map` values ('3', '59');
insert into `role_privilege_map` values ('3', '60');
insert into `role_privilege_map` values ('3', '61');
insert into `role_privilege_map` values ('3', '62');
insert into `role_privilege_map` values ('3', '63');
insert into `role_privilege_map` values ('3', '64');
insert into `role_privilege_map` values ('3', '65');
insert into `role_privilege_map` values ('3', '66');
insert into `role_privilege_map` values ('3', '67');
insert into `role_privilege_map` values ('3', '68');
insert into `role_privilege_map` values ('3', '69');
insert into `role_privilege_map` values ('3', '70');
insert into `role_privilege_map` values ('3', '71');
insert into `role_privilege_map` values ('3', '72');
insert into `role_privilege_map` values ('3', '73');
insert into `role_privilege_map` values ('3', '74');
insert into `role_privilege_map` values ('3', '75');
insert into `role_privilege_map` values ('3', '76');
insert into `role_privilege_map` values ('3', '77');
insert into `role_privilege_map` values ('3', '78');
insert into `role_privilege_map` values ('3', '79');
insert into `role_privilege_map` values ('3', '80');
insert into `role_privilege_map` values ('3', '81');
insert into `role_privilege_map` values ('3', '82');
insert into `role_privilege_map` values ('3', '83');
insert into `role_privilege_map` values ('3', '84');
insert into `role_privilege_map` values ('3', '85');
insert into `role_privilege_map` values ('3', '86');
insert into `role_privilege_map` values ('3', '87');
insert into `role_privilege_map` values ('3', '88');
insert into `role_privilege_map` values ('3', '89');
insert into `role_privilege_map` values ('3', '90');
insert into `role_privilege_map` values ('3', '91');
insert into `role_privilege_map` values ('3', '92');
insert into `role_privilege_map` values ('3', '93');
insert into `role_privilege_map` values ('3', '94');
insert into `role_privilege_map` values ('3', '95');
insert into `role_privilege_map` values ('3', '96');
insert into `role_privilege_map` values ('3', '97');
insert into `role_privilege_map` values ('3', '98');
insert into `role_privilege_map` values ('3', '99');
insert into `role_privilege_map` values ('3', '100');
insert into `role_privilege_map` values ('3', '101');

insert into `role_privilege_map` values ('2', '1');
insert into `role_privilege_map` values ('2', '2');
insert into `role_privilege_map` values ('2', '3');
insert into `role_privilege_map` values ('2', '4');
insert into `role_privilege_map` values ('2', '5');
insert into `role_privilege_map` values ('2', '6');
insert into `role_privilege_map` values ('2', '7');
insert into `role_privilege_map` values ('2', '8');
insert into `role_privilege_map` values ('2', '9');
insert into `role_privilege_map` values ('2', '10');
insert into `role_privilege_map` values ('2', '11');
insert into `role_privilege_map` values ('2', '12');
insert into `role_privilege_map` values ('2', '13');
insert into `role_privilege_map` values ('2', '14');
insert into `role_privilege_map` values ('2', '15');
insert into `role_privilege_map` values ('2', '16');
insert into `role_privilege_map` values ('2', '17');
insert into `role_privilege_map` values ('2', '18');
insert into `role_privilege_map` values ('2', '19');
insert into `role_privilege_map` values ('2', '20');
insert into `role_privilege_map` values ('2', '21');
insert into `role_privilege_map` values ('2', '22');
insert into `role_privilege_map` values ('2', '23');
insert into `role_privilege_map` values ('2', '24');
insert into `role_privilege_map` values ('2', '26');
insert into `role_privilege_map` values ('2', '27');
insert into `role_privilege_map` values ('2', '28');
insert into `role_privilege_map` values ('2', '29');
insert into `role_privilege_map` values ('2', '30');
insert into `role_privilege_map` values ('2', '31');
insert into `role_privilege_map` values ('2', '32');
insert into `role_privilege_map` values ('2', '33');
insert into `role_privilege_map` values ('2', '34');
insert into `role_privilege_map` values ('2', '35');
insert into `role_privilege_map` values ('2', '36');
insert into `role_privilege_map` values ('2', '37');
insert into `role_privilege_map` values ('2', '38');
insert into `role_privilege_map` values ('2', '39');
insert into `role_privilege_map` values ('2', '40');
insert into `role_privilege_map` values ('2', '41');
insert into `role_privilege_map` values ('2', '42');
insert into `role_privilege_map` values ('2', '43');
insert into `role_privilege_map` values ('2', '44');
insert into `role_privilege_map` values ('2', '45');
insert into `role_privilege_map` values ('2', '46');
insert into `role_privilege_map` values ('2', '47');
insert into `role_privilege_map` values ('2', '48');
insert into `role_privilege_map` values ('2', '49');
insert into `role_privilege_map` values ('2', '50');
insert into `role_privilege_map` values ('2', '51');
insert into `role_privilege_map` values ('2', '52');
insert into `role_privilege_map` values ('2', '53');
insert into `role_privilege_map` values ('2', '54');
insert into `role_privilege_map` values ('2', '55');
insert into `role_privilege_map` values ('2', '56');
insert into `role_privilege_map` values ('2', '57');
insert into `role_privilege_map` values ('2', '58');
insert into `role_privilege_map` values ('2', '59');
insert into `role_privilege_map` values ('2', '60');
insert into `role_privilege_map` values ('2', '61');
insert into `role_privilege_map` values ('2', '62');
insert into `role_privilege_map` values ('2', '63');
insert into `role_privilege_map` values ('2', '64');
insert into `role_privilege_map` values ('2', '65');
insert into `role_privilege_map` values ('2', '68');
insert into `role_privilege_map` values ('2', '69');
insert into `role_privilege_map` values ('2', '70');
insert into `role_privilege_map` values ('2', '71');
insert into `role_privilege_map` values ('2', '72');
insert into `role_privilege_map` values ('2', '73');
insert into `role_privilege_map` values ('2', '74');
insert into `role_privilege_map` values ('2', '75');
insert into `role_privilege_map` values ('2', '76');
insert into `role_privilege_map` values ('2', '77');
insert into `role_privilege_map` values ('2', '78');
insert into `role_privilege_map` values ('2', '80');
insert into `role_privilege_map` values ('2', '81');
insert into `role_privilege_map` values ('2', '82');
insert into `role_privilege_map` values ('2', '83');
insert into `role_privilege_map` values ('2', '84');
insert into `role_privilege_map` values ('2', '85');
insert into `role_privilege_map` values ('2', '86');
insert into `role_privilege_map` values ('2', '87');
insert into `role_privilege_map` values ('2', '88');
insert into `role_privilege_map` values ('2', '89');
insert into `role_privilege_map` values ('2', '90');
insert into `role_privilege_map` values ('2', '91');
insert into `role_privilege_map` values ('2', '92');
insert into `role_privilege_map` values ('2', '93');
insert into `role_privilege_map` values ('2', '94');
insert into `role_privilege_map` values ('2', '95');
insert into `role_privilege_map` values ('2', '96');
insert into `role_privilege_map` values ('2', '97');
insert into `role_privilege_map` values ('2', '98');
insert into `role_privilege_map` values ('2', '99');
insert into `role_privilege_map` values ('2', '100');
insert into `role_privilege_map` values ('2', '101');

insert into `role_privilege_map` values ('1', '9');
insert into `role_privilege_map` values ('1', '18');
insert into `role_privilege_map` values ('1', '24');
insert into `role_privilege_map` values ('1', '26');
insert into `role_privilege_map` values ('1', '27');
insert into `role_privilege_map` values ('1', '28');
insert into `role_privilege_map` values ('1', '29');
insert into `role_privilege_map` values ('1', '30');
insert into `role_privilege_map` values ('1', '33');
insert into `role_privilege_map` values ('1', '34');
insert into `role_privilege_map` values ('1', '35');
insert into `role_privilege_map` values ('1', '36');
insert into `role_privilege_map` values ('1', '48');
insert into `role_privilege_map` values ('1', '65');
insert into `role_privilege_map` values ('1', '54');
insert into `role_privilege_map` values ('1', '55');
insert into `role_privilege_map` values ('1', '56');
insert into `role_privilege_map` values ('1', '57');
insert into `role_privilege_map` values ('1', '58');
insert into `role_privilege_map` values ('1', '59');
insert into `role_privilege_map` values ('1', '60');
insert into `role_privilege_map` values ('1', '68');
insert into `role_privilege_map` values ('1', '69');
insert into `role_privilege_map` values ('1', '70');
insert into `role_privilege_map` values ('1', '71');
insert into `role_privilege_map` values ('1', '72');
insert into `role_privilege_map` values ('1', '73');
insert into `role_privilege_map` values ('1', '74');
insert into `role_privilege_map` values ('1', '75');
insert into `role_privilege_map` values ('1', '78');
insert into `role_privilege_map` values ('1', '82');
insert into `role_privilege_map` values ('1', '83');
insert into `role_privilege_map` values ('1', '85');
insert into `role_privilege_map` values ('1', '86');
insert into `role_privilege_map` values ('1', '87');
insert into `role_privilege_map` values ('1', '88');
insert into `role_privilege_map` values ('1', '89');
insert into `role_privilege_map` values ('1', '90');
insert into `role_privilege_map` values ('1', '91');
insert into `role_privilege_map` values ('1', '92');
insert into `role_privilege_map` values ('1', '93');
insert into `role_privilege_map` values ('1', '94');
insert into `role_privilege_map` values ('1', '95');
insert into `role_privilege_map` values ('1', '97');
insert into `role_privilege_map` values ('1', '98');
insert into `role_privilege_map` values ('1', '100');
insert into `role_privilege_map` values ('1', '101');
insert into `role_privilege_map` values ('2', '102');
insert into `role_privilege_map` values ('3', '102');

-- initialize external_role
insert into external_role values(1,"manager");
insert into external_role values(2,"sdm");
insert into external_role values(3,"employee");
insert into external_role values(4,"ssdm");

-- initialize external_role_map
insert into external_role_map values(1,1);
insert into external_role_map values(2,1);
insert into external_role_map values(3,1);
insert into external_role_map values(1,2);
insert into external_role_map values(2,2);
insert into external_role_map values(1,3);
insert into external_role_map values(1,4);
insert into external_role_map values(2,4);

-- initialize assessment_item_type
insert into assessment_item_type values(1,'trainee2plan');
insert into assessment_item_type values(2,'trainee2course');
insert into assessment_item_type values(3,'trainee2trainer');
insert into assessment_item_type values(4,'master2trainer');
insert into assessment_item_type values(5,'trainer2plan');
insert into assessment_item_type values(6,'trainer2trainee');
insert into assessment_item_type values(7,'trainer2planCourse');

-- initialize assessment_item
insert into assessment_item values('1', '_training_arrangement', '1', '_training_arrangement_describe', 0);
insert into assessment_item values('2', '_training_course', '1', '_training_course_describe', 0);
insert into assessment_item values('3', '_training_material', '2', '_training_material_describe', 0);
insert into assessment_item values('4', '_difficulty_to_me', '2', null, 0);
insert into assessment_item values('5', '_valuable_to_me', '2', null, 0);
insert into assessment_item values('6', '_preparation', '3', null, 0);
insert into assessment_item values('7', '_expression', '3', null, 0);
insert into assessment_item values('8', '_interaction', '3', null, 0);
insert into assessment_item values('9', '_time_management', '3', null, 0);
insert into assessment_item values('10', '_responsibility', '4', null, 0);
insert into assessment_item values('11', '_proactive', '4', null, 0);
insert into assessment_item values('12', '_provide_assessment', '4', '_provide_assessment_describe', 0);
insert into assessment_item values('13', '_training_preparation', '4', null, 0);
insert into assessment_item values('14', '_plan_objectives', '5', '_plan_objectives_describe', 0);
insert into assessment_item values('15', '_training_arrangement', '5', '_training_arrangement_describe', 0);
insert into assessment_item values('16', '_training_course', '5', '_training_course_describe', 0);
insert into assessment_item values('18', '_assessment_course_behavior', '6', null, 0);
insert into assessment_item values('19', '_assessment_course_homework', '6', null, 1);
insert into assessment_item values('20', '_planCourse', '7', null, 0);

